#ifndef __ARAVIS_CAMERA_LOG_COMPONENT_HPP__
#define __ARAVIS_CAMERA_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(ARV)

#endif // __ARAVIS_CAMERA_LOG_COMPONENT_HPP__
